version: '3'
services:
  ice:
    build: ice
    hostname: ice
    image: jonbrouse/ice:latest
    command: |
      -Djava.net.preferIPv4Stack=true
      -Djava.net.preferIPv4Addresses
      -Duser.timezone=<Your Timezone ie America/New_York>
      -Dice.s3AccessKeyId=<s3AccessKeyId>
      -Dice.s3SecretKey=<s3SecretKeyId>
      run-app
    volumes:
      - ./ice/assets/ice.properties:/opt/ice/src/java/ice.properties
  nginx:
    hostname: nginx
    image: nginx:1.13.3-alpine
    ports:
      - "80:80"
    links:
      - ice:ice
    volumes:
      - ./nginx/assets/default.conf:/etc/nginx/conf.d/default.conf
